### PR TITLE
Added UI for feedback

### PR DESCRIPTION
**Pull request by khavinshankar**
Resolves https://github.com/coronasafe/ayushma/issues/75

The UI includes,
- thumbs up and down icons for rating
image

- modal for giving additional feedback
image

### CODE REVIEW

**Review by skks1212 — CHANGES_REQUESTED** [review]
@khavinshankar
- All is perfect, just the page is reloading after submit.
- Can we have regular icons for thumbs up/down? `far` instead or `fal`. Also they don't have a `cursor-pointer`
- If a popup opens after hovering on the given feedback icon containing the message it would be nice.
image
- Deploy preview is failing can you look into it?

**Comment by khavinshankar** [comment]
> @khavinshankar
> 
> * All is perfect, just the page is reloading after submit.
> * Can we have regular icons for thumbs up/down? `far` instead or `fal`. Also they don't have a `cursor-pointer`
> * If a popup opens after hovering on the given feedback icon containing the message it would be nice.
>   image
> * Deploy preview is failing can you look into it?

- [x] added a state instead of reloading the page 
- [x] changed fal to far, and added cursor pointer
- [x] added a tooltip for feedback messages on hover
image

**Comment by khavinshankar** [comment]
@skks1212 I'm not able to see the vercel logs, can u add me in that or can u take a screenshot and post it here

**Comment by skks1212** [comment]
@khavinshankar Cannot add you to team, Mathew can. Here are the logs:
image

Is `next lint` not detecting this? Or is husky not configured properly?

**Comment by bodhish** [comment]
@khavinshankar @Ashesh3 do review

**Pull request merged**
