### PR TITLE
Show project chats to admin

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes [#266](https://github.com/coronasafe/ayushma/issues/266)

Waiting for backend [#334](https://github.com/coronasafe/ayushma/pull/334)

Show the project chats to the admin in descending order of creation
image

Show chats list along with username
image

Show the user and the chats
image

Clicking the user redirects to the user's admin page
image

### CODE REVIEW

**Comment by skks1212** [comment]
@Pranshu1902 will be great if we are able to view the user who created the chat

**Comment by Pranshu1902** [comment]
> @Pranshu1902 will be great if we are able to view the user who created the chat

@skks1212 done

**Comment by skks1212** [comment]
@Pranshu1902 merge conflicts!

**Comment by Pranshu1902** [comment]
@skks1212 resolved!

**Comment by Pranshu1902** [comment]
@skks1212 done, added a common table component
image

**Comment by Pranshu1902** [comment]
@skks1212 check now

**Comment by skks1212** [comment]
@Pranshu1902 is this link broken?
image

**Comment by Pranshu1902** [comment]
@skks1212 fixed the link

**Comment by skks1212** [comment]
@Pranshu1902 opening details shows no chats found until it loads them. Can we use the loading state here from react query?

**Review by skks1212 — APPROVED** [review]
LGTM

**Pull request merged**
