### PR TITLE
Remember language for a conversation

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes https://github.com/coronasafe/ayushma/issues/459

This pull request adds a new prop `forceLanguage` to the `ChatBar` component, which allows the language to be overridden and prevents it from being changed after the conversation has started. This functionality is useful when there is a need to enforce a specific language for the conversation.

### CODE REVIEW

**Comment by skks1212** [comment]
@Ashesh3 is this able to be toggled on/off? If I want to change my language mid conversation for some specific use case it should be allowed. Maybe add this to the settings modal

**Comment by Ashesh3** [comment]
> @Ashesh3 is this able to be toggled on/off? If I want to change my language mid conversation for some specific use case it should be allowed. Maybe add this to the settings modal

We're decided against language changes mid conversation.
Ref: https://github.com/coronasafe/ayushma_fe/issues/163

**Comment by Ashesh3** [comment]
@skks1212 could you review it?

**Comment by skks1212** [comment]
Looks good to me. Maybe we can do the toggle thing in another PR

**Review by skks1212 — APPROVED** [review]

**Pull request merged**
