### PR TITLE
Added env var for optional logo

### PR DESCRIPTION
**Pull request by suprabathk**
Fixes: #86

### CODE REVIEW

**Review by bodhish — CHANGES_REQUESTED** [review]
- [ ] Use 1 logo for all pages 
- [ ] Clean up unused assets from the app. (other logos)

**Comment by suprabathk** [comment]
Removed Admin Logo and using same logo as User

**Comment by suprabathk** [comment]
We have [logo.png](https://github.com/coronasafe/ayushma_fe/blob/master/public/logo.png) in assets it's being used only in README.md
We already have it's svg version. ([logo.svg](https://github.com/coronasafe/ayushma_fe/blob/master/public/logo.svg))

Should we remove it?

**Comment by bodhish** [comment]
If we can use the svg in readme why not remove it

**Comment by suprabathk** [comment]
@bodhish 
Done, Removed logo.png as well

**Review by skks1212 — APPROVED** [review]

**Pull request merged**
